# Generated by Django 4.0.2 on 2022-03-07 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='grade',
            new_name='is_correct',
        ),
    ]
